In [6]:
def isprime(n):
    for i in range(2,n):
        if(n%i==0):
            return False
    return True
def isemirp(n):
    n=str(n)
    if n==n[::-1]:
        return False
    return isprime(int(n[::-1]))
def isbemirp(n):
    n=str(n)
    num=''
    for i in n:
        if i=='6':
            num+='9'
        elif i=='9':
            num+='6'
        else:
            num+=i
    return isemirp(int(num))

n=int(input())
for i in range(n):
    num=int(input())
    status='C'
    if isprime(num):
        status='P'
        if isemirp(num):
            status='E'
            if isbemirp(num):
                status='B'
    print(status)
    



4
101
P
1011
C
1069
E
1061
B


In [12]:
def sum_of_prime_factors(n):
    s=0
    for i in range(2,n):
        if n%i==0:
            if isprime(i):
                s=s+i
    return s
n=int(input())
for i in range(n):
    num=list(map(int,input().split()))
    f = sum_of_prime_factors(num[0])
    s = sum_of_prime_factors(num[1])
    if f == s:
        print("True") 
    else:
        print("False")

    

1
24 25
True


# Numpy

In [1]:
import numpy as np
l=[1,2,3,4]
print(np.array(l))

[1 2 3 4]


In [3]:
import numpy as np
l=[[1,2],[3,4]]
print(np.array(l))

[[1 2]
 [3 4]]


In [6]:
import numpy as np
l=[1,2,3,4]
l=l+2
print(np.array(l))

TypeError: can only concatenate list (not "int") to list

In [11]:
import numpy as np
#l=[1,2,3,4]
l=[1,"ding",30,40]

print(np.array(l,dtype='object')) //int,float,bool,object,str

[1 'ding' 30 40]


In [14]:
import numpy as np
#l=[1,2,3,4]
l=[[1,0,3],['4','5','6']]
a=np.array(l,dtype='int')
print(a)



[[1 0 3]
 [4 5 6]]


In [15]:
#tolist
a.tolist()

[[1, 0, 3], [4, 5, 6]]

In [16]:
a

array([[1, 0, 3],
       [4, 5, 6]])

In [18]:
a.shape

(2, 3)

In [19]:
a.dtype

dtype('int32')

In [21]:
#number of dimenstions
a.ndim

2

In [20]:
#size of array
a.size


6